apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimath
spec:
  selector:
    matchLabels:
      app: apimath
  template:
    metadata:
      labels:
        app: apimath
    spec:
      containers:
        - name: apimath
          image: apimath
          ports:
            - containerPort: 8080
