name: Continuous Deployment
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      repository: renasti/desafio-altbk
      username: renasti
    permissions:
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Tests
        run: go test -v ./handlers/...

      - name: build image & push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ env.username }}
          password: ${{ secrets.PWD_DOCKER }}
          repository: ${{ env.repository }}
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update kubernetes
        run: |
          cd k8s
          kustomize edit set image apimath=renasti/desafio-altbk:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy..."
          git commit -am "Changing image tag"

      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
